/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pogledi.forme;

import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author milos
 */
public class FormaAutomobil extends javax.swing.JDialog {

    /**
     * Creates new form FormaAutomobili
     */
    public FormaAutomobil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        radioGrupa.add(radioPostojeci);
        radioGrupa.add(radioNovi);
    }

    public JButton getBtnSacuvaj() {
        return btnSacuvaj;
    }

    public JComboBox<String> getCbGorivo() {
        return cbGorivo;
    }

    public JComboBox getCbMarka() {
        return cbMarka;
    }

    public JComboBox getCbModel() {
        return cbModel;
    }

    public JComboBox<String> getCbSegment() {
        return cbSegment;
    }

    public JPanel getPanelNovi() {
        return panelNovi;
    }

    public JPanel getPanelPostojeci() {
        return panelPostojeci;
    }

    public ButtonGroup getRadioGrupa() {
        return radioGrupa;
    }

    public JRadioButton getRadioPostojeci() {
        return radioPostojeci;
    }

    public JRadioButton getRadioNovi() {
        return radioNovi;
    }

    public JTextField getTxtCena() {
        return txtCena;
    }

    public JTextField getTxtGodiste() {
        return txtGodiste;
    }

    public JTextField getTxtJacinaMotora() {
        return txtJacinaMotora;
    }

    public JTextField getTxtKilometraza() {
        return txtKilometraza;
    }

    public JTextField getTxtKubikaza() {
        return txtKubikaza;
    }

    public JTextField getTxtOznaka() {
        return txtOznaka;
    }

    public JTextField getTxtPotrosnja() {
        return txtPotrosnja;
    }

    public JTextField getTxtRegistracija() {
        return txtRegistracija;
    }

    public void addBtnSacuvajActionListener(ActionListener actionListener) {
        btnSacuvaj.addActionListener(actionListener);
    }

    public void addRadioPostojeciActionListeners(ActionListener actionListener) {
        radioPostojeci.addActionListener(actionListener);
    }

    public void addRadioNoviActionListener(ActionListener actionListener) {
        radioNovi.addActionListener(actionListener);
    }

    public void addBtnIzmeniActionListener(ActionListener actionListener) {
        btnIzmeni.addActionListener(actionListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGrupa = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        txtJacinaMotora = new javax.swing.JTextField();
        txtGodiste = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        radioPostojeci = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        radioNovi = new javax.swing.JRadioButton();
        txtKilometraza = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        txtPotrosnja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelPostojeci = new javax.swing.JPanel();
        cbModel = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbGorivo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelNovi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbMarka = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtOznaka = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbSegment = new javax.swing.JComboBox<>();
        txtRegistracija = new javax.swing.JTextField();
        txtKubikaza = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setText("Godiste:");

        btnSacuvaj.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSacuvaj.setText("Sacuvaj");

        radioPostojeci.setText("Postojeći model");
        radioPostojeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPostojeciActionPerformed(evt);
            }
        });

        jLabel7.setText("Kilometraza:");

        radioNovi.setText("Novi model");

        jLabel8.setText("Cena:");

        jLabel4.setText("Tip goriva:");

        panelPostojeci.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cbModel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelPostojeciLayout = new javax.swing.GroupLayout(panelPostojeci);
        panelPostojeci.setLayout(panelPostojeciLayout);
        panelPostojeciLayout.setHorizontalGroup(
            panelPostojeciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPostojeciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbModel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPostojeciLayout.setVerticalGroup(
            panelPostojeciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPostojeciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel9.setText("Potrosnja:");

        cbGorivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dizel", "Benzin", "Hibrid", "Elektricni" }));

        jLabel10.setText("Kubikaza:");

        jLabel5.setText("Registracija:");

        jLabel11.setText("Jacina motora:");

        panelNovi.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Marka:");

        cbMarka.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Oznaka:");

        jLabel3.setText("Segment:");

        cbSegment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mini", "Mali", "Srednji", "Kupe", "Limuzina", "SUV", "Off-road", "Karavan" }));

        javax.swing.GroupLayout panelNoviLayout = new javax.swing.GroupLayout(panelNovi);
        panelNovi.setLayout(panelNoviLayout);
        panelNoviLayout.setHorizontalGroup(
            panelNoviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoviLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNoviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelNoviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOznaka)
                    .addComponent(cbMarka, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbSegment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelNoviLayout.setVerticalGroup(
            panelNoviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoviLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNoviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNoviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOznaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNoviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbSegment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIzmeni.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnIzmeni.setText("Izmeni");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelNovi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPostojeci, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(radioPostojeci)
                                .addGap(18, 18, 18)
                                .addComponent(radioNovi))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPotrosnja)
                                    .addComponent(cbGorivo, 0, 355, Short.MAX_VALUE)
                                    .addComponent(txtGodiste)
                                    .addComponent(txtKilometraza)
                                    .addComponent(txtCena)
                                    .addComponent(txtKubikaza)
                                    .addComponent(txtJacinaMotora)
                                    .addComponent(txtRegistracija))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPostojeci)
                    .addComponent(radioNovi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPostojeci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbGorivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGodiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtKilometraza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPotrosnja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtKubikaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtJacinaMotora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioPostojeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPostojeciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPostojeciActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<String> cbGorivo;
    private javax.swing.JComboBox cbMarka;
    private javax.swing.JComboBox cbModel;
    private javax.swing.JComboBox<String> cbSegment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelNovi;
    private javax.swing.JPanel panelPostojeci;
    private javax.swing.ButtonGroup radioGrupa;
    private javax.swing.JRadioButton radioNovi;
    private javax.swing.JRadioButton radioPostojeci;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtGodiste;
    private javax.swing.JTextField txtJacinaMotora;
    private javax.swing.JTextField txtKilometraza;
    private javax.swing.JTextField txtKubikaza;
    private javax.swing.JTextField txtOznaka;
    private javax.swing.JTextField txtPotrosnja;
    private javax.swing.JTextField txtRegistracija;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnIzmeni() {
        return btnIzmeni;
    }
}
